### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Coooolfan** [Coooolfan/XiaomiAlbumSyncer#1]
无规律地出现
AttributeError: 'NoneType' object has no attribute 'get'

```bash
Traceback (most recent call last):
  File "main.py", line 97, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "main.py", line 94, in cli
  File "nest_asyncio.py", line 30, in run
  File "nest_asyncio.py", line 98, in run_until_complete
  File "asyncio/futures.py", line 203, in result
  File "asyncio/tasks.py", line 314, in __step_run_and_handle_result
  File "main.py", line 51, in icli
  File "src/task.py", line 154, in select_and_download_single_album
  File "src/task.py", line 129, in download_single_album
  File "src/task.py", line 40, in get_all_media_from_album
  File "src/api.py", line 77, in get_media_list
AttributeError: 'NoneType' object has no attribute 'get'
[PYI-2569213:ERROR] Failed to execute script 'main' due to unhandled exception!
```

**Comment by Coooolfan** [comment]
<https://github.com/Coooolfan/XiaomiAlbumSyncer/releases/tag/0.2.1>
