### ISSUE TITLE
BUG 更新相册报错

### ISSUE THREAD

**Issue by bestruirui** [Coooolfan/XiaomiAlbumSyncer#3]
```? 欢迎回来，准备干些什么捏 更新相册列表
Traceback (most recent call last):
  File "/app/main.py", line 119, in <module>
    cli()
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 115, in cli
    asyncio.run(icli())
  File "/usr/local/lib/python3.12/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/app/main.py", line 50, in icli
    await task_update_album_list()
  File "/app/src/task.py", line 124, in update_album_list
    album_list = await get_album_list()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/api.py", line 56, in get_album_list
    raise Exception(response.text)
Exception: {"R":401,"S":"Err","D":"https://account.xiaomi.com/pass/serviceLogin?callback=","E":false,"isSecondValidation":true}
```

**Comment by Coooolfan** [comment]
应该是无效cookie导致的，尝试删除Cookie.json文件后，重新设置cookie

小米云服务的Cookie的有效期很短，条件允许可以每分钟更新一次

**Comment by bestruirui** [comment]
找到问题了，好像是IP的问题，在新的IP上登陆，会有一个验证，需要在浏览器手动过一下就好了

**Comment by Coooolfan** [comment]
> 找到问题了，好像是IP的问题，在新的IP上登陆，会有一个验证，需要在浏览器手动过一下就好了

哈喽，请问这个验证要在哪打开

**Comment by bestruirui** [comment]
浏览器开个隐私窗口试试？
或者换个IP？
我也不太确定，出现的条件

**Comment by Coooolfan** [comment]
> 浏览器开个隐私窗口试试？ 或者换个IP？ 我也不太确定，出现的条件

是在本地直接打开一个浏览器吗，然后程序和浏览器是同一台电脑🤔

**Comment by bestruirui** [comment]
试试在一个从来没有登陆过的设备，首次登录？

**Comment by Zenmiao** [comment]
遇到了类似的问题，直接复制小米云页面的cookie会报错，这时点进云相册会要求验证短信，完成获取到的cookie就可以正常使用
